### ISSUE TITLE
src自动化平台开发日记

### ISSUE THREAD

**Issue by boy-hack** [boy-hack/boy-hack#40]
记录📝点啥..

**Comment by N407PengYuYan** [comment]
收到

**Comment by boy-hack** [comment]
前端记录: https://x.hacking8.com/post-439.html
沿用w12scan的前端框架，把它改成了vue的，工程量还是很大的，但这方面不应该消耗很多时间，简单做了雏形，后面再深入优化

**Comment by boy-hack** [comment]
一个纯go实现的资产收集工作流，subfinder -> ns发现 -> 域传送检测 -> ksubdomain

subfinder的结果会和ksubdomain内置的域名结合再去重。

集成到了一个代码里，这样直接编译一个exe就直接可以跑了,附件是源代码
https://t.zsxq.com/IAU3ney
