### ISSUE TITLE
Django 记录

### ISSUE THREAD

**Issue by boy-hack** [boy-hack/boy-hack#42]
文档: 
- https://docs.djangoproject.com/zh-hans/4.0/
- https://docs.djangoproject.com/zh-hans/3.2/
- https://www.django-rest-framework.org/

### model choices
```python
JobTypes = [
	(0,"技术类"),
	(1,"产品类")
]

DEGREE_TYPE= (("本科","本科"),("博士","博士"))

class Job(models.Model):
	job_type = models.SmallIntegerField(black=True,choices=JobTypes,verbose_name="职位类别")
	degree = models.CharField(max_length=135,blank=True,choices=DEGREE_TYPE,verbose_name="学历")
```

### admin.py

class JobAdmin(admin.ModelAdmin):
	exclude = ('') # 不显示字段
	list_display=() # 列表显示的字段

	action = () # 列表操作
	# 当字段比较多的时候，可以分栏目显示，fields可以合并到一行显示
	fieldsets = (
		(None,{"fields":("字段1","字段2")}),
		("分栏目1",{"fields":("分栏目1-字段1","分栏目1-字段2")}),
	)

### django 添加命令行工具
app里创建文件 management/commands/import_candidates.py

class Command(BaseCommand):
	help = '从一个csv文件内容读取候选人列表，倒入数据库中'

	def add_arguments(self,parser):
		parser.add_arguments('--path',type=str)

	def handle(self,*args,**kwargs):
		pass

### 日志
在Settings设置日志

主动调用
import logging
loggerr = logging.getLoger(__name__)

### 10行代码注册model
在apps.py 中
from django.app import apps

class AdminClass(admin.Model):
	def __init__(self,model):
		self.list_display = [field.name for field in model._meta.fields]
		super(AdminClass,self).__init__(model,admin_site)

class UniversalManagerApp(AppConfig):
	def ready(self):
		models = apps.get_app_config("appName").get_models()
		for model in models:
			try:
				admin.site.register(model)
			except admin.sites.AlreadyRegister:
				pass

**Comment by boy-hack** [comment]
`settings.py`

```python

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

APPEND_SLASH = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/data/static'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
```

**Comment by boy-hack** [comment]
### django rest framework

[https://www.cnblogs.com/FutureHolmes/p/13967358.html](https://www.cnblogs.com/FutureHolmes/p/13967358.html)

**Comment by N407PengYuYan** [comment]
收到
